export const devices = [
  {
    id: 1,
    icon: '',
    status: 'Off',
    name: 'Switch 1.1',
    location: 'Living Room',
  },
  {
    id: 2,
    icon: '',
    status: 'Off',
    name: 'Switch 1.2',
    location: 'Living Room',
  },
  {
    id: 3,
    icon: '',
    status: 'Off',
    name: 'Switch 1.3',
    location: 'Living Room',
  },
  {
    id: 4,
    icon: '',
    status: 'Off',
    name: 'Switch 1.4',
    location: 'Living Room',
  },
  {
    id: 5,
    icon: '',
    status: 'Off',
    name: 'Switch 2.1',
    location: 'Living Room',
  },
  {
    id: 6,
    icon: '',
    status: 'Off',
    name: 'Switch 2.2',
    location: 'Living Room',
  },
  {
    id: 7,
    icon: '',
    status: 'Off',
    name: 'Switch 2.3',
    location: 'Living Room',
  },
];
